import Head from 'next/head'
import Image from 'next/image'
import HeroMain from '../assets/hero_images.png'
import Layout from '../components/Layout'
import { software, banner_2 } from '../data/software'
import FeaturedCard from '../components/FeaturedCard'
import SliderCustomer from '../components/SliderCustomer'
import customers from '../data/customers'
import Banner2 from '../assets/banner2_img.png'
import ERPSection from '../components/ERPSection'
import SliderTestimony from '../components/SliderTestimony'
import BusinessSolution from '../components/BusinessSolution'
import ContactSection from '../components/ContactSection'
import RequestDemo from '../components/RequestDemo'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useRef } from 'react'

export default function Home() {
  const { t } = useTranslation('home')
  const ref = useRef(null)

  return (
    <div className='relative'>
      <Head>
        <title>Yubi | Software Solution</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* Navigation */}

      <main>
        {/* Hero */}
        <section className='relative  h-[95vh] overflow-hidden md:h-screen'>
          <div className='mx-auto max-w-screen-lg px-8 pt-24 md:px-10 md:pt-28 xl:max-w-screen-md 2xl:max-w-screen-xl '>
            <h1 className='mb-6 text-2xl font-bold text-white md:text-center md:text-5xl lg:mx-auto lg:max-w-3xl lg:text-4xl 2xl:max-w-screen-2xl 2xl:px-32 2xl:px-20 2xl:text-6xl'>
              {t('hero.hero_title')}
            </h1>
            <p className='mx-auto text-white  md:max-w-xl md:text-center'>
              {t('hero.hero_subtitle')}
            </p>
            <div className='mt-8 flex select-none items-center space-x-4  md:justify-center'>
              <button
                onClick={() =>
                  ref.current.scrollIntoView({
                    behavior: 'smooth',
                    block: 'end',
                  })
                }
                className='btn-outline large-mobile:text-base border-white text-sm  hover:bg-white hover:text-gray-600 '
              >
                {t('hero.hero_action_cta')}
              </button>
              <a
                href='https://wa.me/+6281290049231'
                target='_blank'
                rel='noopener noreferrer'
                className='btn large-mobile:text-base bg-primaryBrand text-sm hover:bg-primaryBrand/80 hover:text-opacity-100 hover:shadow-md active:scale-95 active:bg-primaryBrand'
              >
                {t('hero.hero_action_message')}
              </a>
            </div>
          </div>
          <div className='absolute bottom-0 -z-10 mx-auto w-screen '>
            <div className='large-mobile:translate-x-1 relative mx-auto w-[45vh] translate-x-0 overflow-hidden opacity-90 sm:w-[50vh] md:w-[60vh] 2xl:w-[80vh]  '>
              <Image
                className='ml-12 w-full'
                layout='responsive'
                src={HeroMain}
                alt='product with devices'
              />
            </div>
          </div>
          <div className='absolute top-0 -z-20 min-h-[90vh] w-screen bg-gradient-to-tr from-secondaryBrand to-primaryBrand'></div>
        </section>
        {/* Featured */}
        <section ref={ref} className='min-h-[70vh]'>
          <Layout className='relative '>
            <h1 className='text-2xl font-bold'>Featured Software</h1>
            <div className='mt-4 grid grid-cols-1 gap-y-2 md:grid-cols-2 md:gap-y-0 md:gap-x-1 lg:gap-x-3 lg:gap-y-6'>
              {software.map((data, index) => (
                <FeaturedCard key={index} data={data} />
              ))}
            </div>
            <div className='mx-auto mt-4 w-full md:mt-8 lg:max-w-screen-lg'>
              <SliderCustomer customers={customers} />
            </div>
          </Layout>
        </section>
        {/* Yubi Features */}
        <section className='lg:min-h-[80vh]'>
          <Layout>
            <div className='mt-8 flex flex-col md:flex-row md:space-x-6'>
              <div className='h-auto w-full lg:w-1/2'>
                <div className='relative mx-auto h-80 rounded-lg md:h-[60vh]  lg:max-w-sm'>
                  <Image
                    className='rounded-xl'
                    src={Banner2}
                    layout='fill'
                    objectFit='cover'
                    alt='banner 2 girl'
                  />
                </div>
              </div>
              <div className='py-4 lg:w-1/2 lg:py-8 '>
                <h1 className='text-2xl text-3xl font-bold md:mb-4 xl:text-4xl 2xl:text-5xl'>
                  {t('feature-yubi.title')}
                </h1>
                <div className='mt-4 h-[80%] w-full space-y-6  md:space-y-8 lg:mt-8  lg:flex lg:max-w-md lg:flex-col lg:justify-evenly lg:space-y-8'>
                  {banner_2.map((data, index) => (
                    <div key={data.id} className='flex space-x-2 md:space-x-4 '>
                      <h1 className='text-xl font-bold text-slate-500 xl:text-3xl 2xl:text-4xl'>
                        {t(`feature-yubi.descriptions.${data.id}.id`)}
                      </h1>
                      <div>
                        <h2 className='font-bold text-slate-900 md:text-xl lg:text-2xl  2xl:text-2xl'>
                          {t(`feature-yubi.descriptions.${data.id}.title`)}
                        </h2>
                        <p className='text-sm md:mt-2 md:text-base'>
                          {t(
                            `feature-yubi.descriptions.${data.id}.description`
                          )}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </Layout>
        </section>
        {/* ERP */}
        <ERPSection />
        {/* Testimonial */}
        <SliderTestimony />
        {/* Business Solution */}
        <BusinessSolution />

        {/* Contact Us */}
        <ContactSection />

        {/* Request Demo CTA */}
        <RequestDemo />

        {/* Footer */}
      </main>
    </div>
  )
}

export const getStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['nav', 'common', 'home'])),
    },
  }
}
